import { test, expect } from "@playwright/test";
// Logs in -> Adds item to cart -> Place order -> Verify if order shows up on orders page
// test.describe.configure({ mode: "parallel" });

const userName = "Normal User";
const email = "cs4218@test.com";
const address = "1 Computing Drive";
const pwd = "cs4218@test.com"

test.describe("Test orders placed and reflected on orders page", () => {
    test.beforeEach(async({page}) => {
        await page.goto("/login");
        const userNameInput = page.getByPlaceholder("Enter Your Email");
        const pwdInput = page.getByPlaceholder("Enter Your Password");
        const submitButton = page.getByText("LOGIN", { exact: true });

        await userNameInput.fill(email);
        await pwdInput.fill(pwd);
        await submitButton.click();     // we navigate to homepage
    });

    test("Check if orders sequence works properly", async ({ page }) => {
        const homePageHeading = page.getByRole("heading", {name: "All Products"});
        const elementToBeAddedToCart = page.getByTestId("add-to-cart-novel");
        const cartPage = "/cart"

        await expect(homePageHeading).toBeVisible();
        await expect(elementToBeAddedToCart).toBeVisible();
        await elementToBeAddedToCart.click();
        await expect(page.getByText("Item added to cart")).toBeVisible();
        await page.goto(cartPage);

        // Generated by ChatGPT
        // Click on the "Card" option inside the drop-in UI
        await expect(page.getByText("Choose a way to pay")).toBeVisible({ timeout: 10000 });
        await page.getByRole("button", { name: "Paying with Card" }).click();

        // Wait for the Braintree card iframes to appear
        await page.waitForSelector('iframe[name*="braintree-hosted-field-number"]', { timeout: 15000 });
        await page.waitForSelector('iframe[name*="braintree-hosted-field-expiration"]', { timeout: 15000 });
        await page.waitForSelector('iframe[name*="braintree-hosted-field-cvv"]', { timeout: 15000 });

        // Define frame locators
        const numberFrame = page.frameLocator('iframe[name*="braintree-hosted-field-number"]');
        const expiryFrame = page.frameLocator('iframe[name*="braintree-hosted-field-expiration"]');
        const cvvFrame = page.frameLocator('iframe[name*="braintree-hosted-field-cvv"]');

        // Fill card details using Braintree's data attributes
        await numberFrame.locator('input[data-braintree-name="number"]').fill('4111 1111 1111 1111');
        await expiryFrame.locator('input[data-braintree-name="expirationDate"]').fill('12/27');
        await cvvFrame.locator('input[data-braintree-name="cvv"]').fill('123');
        // Click "Make Payment"
        await page.getByRole('button', { name: 'Make Payment' }).click();


        // Must be redirected to orders page
        await expect(page.getByText("All Orders")).toBeVisible();

    await expect(page.getByTestId("order-number-1")).toHaveText("1");
    await expect(page.getByTestId("order-status-1")).toHaveText("Not Processed");
    await expect(page.getByTestId("order-buyer-1")).toHaveText("Normal User");
    await expect(page.getByTestId("order-payment-1")).toHaveText("Success");
    await expect(page.getByTestId("order-date-1")).toHaveText("a year ago");
    await expect(page.getByTestId("product-name-66db427fdb0119d9234b27f9")).toHaveText("Novel");
    await expect(page.getByTestId("product-desc-66db427fdb0119d9234b27f9")).toHaveText("A bestselling novel");
    await expect(page.getByTestId("product-price-66db427fdb0119d9234b27f9")).toHaveText("Price : 14.99");
});
